### ISSUE TITLE
"TypeError: Cannot set property 'props' of undefined" in graphql query when using diqus plugin with contentful

### ISSUE THREAD

**Issue by Ben1980** [tterb/gatsby-plugin-disqus#33]
As soon a si configure gatsby-plugin-disqus in gatsby-config.js the graphql queries against contentful are not working anymore

```
{
  resolve: `gatsby-plugin-disqus`,
  options: {
    shortname: `thoughts-on-coding`,
  }
},
```

Error:
```
{
  "errors": [
    {
      "message": "Cannot set property 'props' of undefined",
      "locations": [
        {
          "line": 5,
          "column": 9
        }
      ],
      "path": [
        "contentfulBlogPost",
        "description",
        "childMarkdownRemark",
        "html"
      ],
      "stack": [
        "TypeError: Cannot set property 'props' of undefined",
        "    at Component (/home/bmahr/develop/thoughts-on-coding/node_modules/react/cjs/react.development.js:428:14)",
        "    at Disqus (/home/bmahr/develop/thoughts-on-coding/node_modules/gatsby-plugin-disqus/components/Disqus.js:28:30)",
        "    at /home/bmahr/develop/thoughts-on-coding/node_modules/gatsby-transformer-remark/extend-node-type.js:227:18",
        "    at processImmediate (internal/timers.js:461:21)",
        "From previous event:",
        "    at parseString (/home/bmahr/develop/thoughts-on-coding/node_modules/gatsby-transformer-remark/extend-node-type.js:220:21)",
        "    at getMarkdownAST (/home/bmahr/develop/thoughts-on-coding/node_modules/gatsby-transformer-remark/extend-node-type.js:272:14)",
        "    at getAST (/home/bmahr/develop/thoughts-on-coding/node_modules/gatsby-transformer-remark/extend-node-type.js:180:36)",
        "    at getHTMLAst (/home/bmahr/develop/thoughts-on-coding/node_modules/gatsby-transformer-remark/extend-node-type.js:365:21)",
        "    at getHTML (/home/bmahr/develop/thoughts-on-coding/node_modules/gatsby-transformer-remark/extend-node-type.js:379:21)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)"
      ]
    }
  ],
  "data": {
    "contentfulBlogPost": {
      "description": {
        "childMarkdownRemark": {
          "html": null
        }
      }
    }
  },
  "extensions": {}
}
```

To reproduce clone my repository ([https://github.com/Ben1980/thoughts-on-coding](https://github.com/Ben1980/thoughts-on-coding)) and connect it with your own contenful account.
With
```
query MyQuery {
  contentfulBlogPost {
    description {
      childMarkdownRemark {
        html
      }
    }
  }
}
```
you can reproduce the issue.

**Specifications:**
 - gatsby-plugin-disqus: 1.2.2
 - gatsby-source-contentful: 4.2.1
 - Gatsby version: 2.28.2

**Comment by tterb** [comment]
@Ben1980 From you're sites `package.json` and `components/comments.js`, it looks like your site is using the [`disqus-react`](https://github.com/disqus/disqus-react) package and not this plugin. 
So you would need to either modify those to use `gatsby-plugin-disqus` or follow the usage documentation for [`disqus-react`](https://github.com/disqus/disqus-react).

**Comment by Ben1980** [comment]
yes, I moved on with disqus-react because the plugin wasn't working and I needed a solution.
